version: "3.7"

services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /home/choppy/Files/AppData/Config/audiobookshelf/audiobooks:/audiobooks
      - /home/choppy/Files/AppData/Config/audiobookshelf/podcasts:/podcasts
      - /home/choppy/Files/AppData/Config/audiobookshelf/metadata:/metadata
      - /home/choppy/Files/AppData/Config/audiobookshelf:/config
